apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grapevine-base

resources:
  # Namespaces
  - namespaces.yaml

  # Services and workers
  - grapevine-services/
  - grapevine-workers/

# Common labels applied to all resources
labels:
  - pairs:
      app.kubernetes.io/part-of: grapevine
