name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit to promote to production from staging'
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false # We only want to run one at a time.

permissions:
  contents: write # Push up new branch
  pull-requests: write # Create promotion PR
  checks: write # Create check on promotion PR

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: ./.github/actions/setup-tools
        with:
          github_token: ${{ github.token }}
          working_directory: '.github/actions/promote'

      - name: Get Go directories
        id: go
        working-directory: '.github/actions/promote'
        run: |
          echo "cache_dir=$(go env GOCACHE)" >> "$GITHUB_OUTPUT"
          echo "mod_cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.go.outputs.cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-build-cache-${{ hashFiles('.github/actions/promote/go.sum') }}
      - uses: actions/cache@v4
        with:
          path: ${{ steps.go.outputs.mod_cache_dir }}
          key: ${{ github.workflow }}-${{ runner.os }}-go-mod-cache-${{ hashFiles('.github/actions/promote/go.sum') }}

      - name: Create Promotion PR
        working-directory: '.github/actions/promote'
        env:
          COMMIT: ${{ inputs.commit_sha }}
          ENVIRONMENT: 'production'
          GITHUB_TOKEN: ${{ github.token }}
        run: mise run promote-run create-pr "$COMMIT" "$ENVIRONMENT"
